name: shipper_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  ## These are the packages supported by both "Android" & "Web" ##
  aws_sesv2_api: ^2.0.0
  shared_preferences: ^2.0.18
  sizer: ^2.0.15
  firebase_auth:
  firebase_core:
  firebase_database:
  pin_code_fields: ^7.4.0
  flutter_dotenv: ^5.0.2
  http: ^0.13.3
  get: ^4.3.8
  intl: ^0.17.0
  geolocator: ^9.0.2
  syncfusion_flutter_charts: ^20.4.53
  provider: ^6.0.5
  google_maps_flutter_web: ^0.4.0+6
  flutter_polyline_points: ^1.0.0
  flutter_spinkit: ^5.0.0
  get_storage: ^2.0.3
  pinput: ^2.2.11
  modal_progress_hud_alt: ^1.0.0
  image_picker: ^0.8.4
  url_launcher: ^6.0.9
  date_format: ^2.0.2
  jiffy: ^5.0.0
  otp_text_field: ^1.1.1
  firebase_messaging: ^14.2.6
  translator: ^0.1.7
  overlay_support: ^2.0.1
  shimmer: ^2.0.0
  screenshot: ^1.2.3
  flutter_easyloading: ^3.0.5
  marquee: ^2.2.3
  permission_handler_web: ^0.0.2
  package_info_plus: ^3.0.3
  firebase_remote_config: ^3.0.14
  visibility_aware_state: ^1.0.5
  fluster: ^1.2.0
  google_maps_cluster_manager: ^3.0.0+1
  date_time_picker: ^2.1.0
  pull_to_refresh: ^2.0.0
  connectivity_plus: ^3.0.3
  flutter_google_places: ^0.3.0
  dotted_line: ^3.1.0
  flutter_animarker: ^3.2.0
  async: ^2.10.0
  flutter_mapbox_autocomplete: ^2.0.0
  speech_to_text: ^6.1.1
  webview_flutter_web: ^0.2.2+1
  font_awesome_flutter: ^10.4.0
  fluttertoast: ^8.2.1
  logger: ^1.2.2
  google_sign_in: ^6.0.2
  flutter_map_marker_popup: ^4.0.2

  ## End of packages supported by both "Android" & "Web" ##

  ## These are the packages supported by only "Android"##
#
  #  geocoding: ^2.0.2
  geocoding: ^2.1.0
  google_maps_flutter: ^2.2.5
  social_share: ^2.1.1
  firebase_dynamic_links: ^5.0.16
  wc_flutter_share: ^0.4.0
  permission_handler: ^10.2.0
  onesignal_flutter: ^3.0.0
  package_info: ^2.0.2
  device_info: ^2.0.2
  flutter_background: ^1.0.2+1
  flutter_cache_manager: ^3.1.2
  connectivity: ^3.0.6
  flutter_gifimage: ^1.0.0
  custom_info_window: ^1.0.1
  share: ^2.0.4
  gallery_saver: ^2.3.2
  webview_flutter: ^4.0.1

  ## End of packages supported by only "Android"##

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/background/
    - assets/icons/navigationIcons/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
