// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd0O5dKTa31uoOWxWMvTy2CafP_C7VfN0',
    appId: '1:692017725889:web:cc19a50e3d57b46959ef40',
    messagingSenderId: '692017725889',
    projectId: 'shipperwebapp',
    authDomain: 'shipperwebapp.firebaseapp.com',
    databaseURL: 'https://shipperwebapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shipperwebapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwGra6d7Gm2fIIp_KUjKKmbVXADbA9iNo',
    appId: '1:692017725889:android:97de2700f739792859ef40',
    messagingSenderId: '692017725889',
    projectId: 'shipperwebapp',
    databaseURL: 'https://shipperwebapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shipperwebapp.appspot.com',
  );
}
